services:
  web:
    build: .
    container_name: hrm-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - hrm-network
    restart: always

networks:
  hrm-network:
    driver: bridge